/**
 * API-DTO Link 路由定義
 */

import { Router } from 'express';
import { ApiDtoLinkController } from '../controllers/apiDtoLink.controller';
import { validate } from '../middlewares/validate';
import {
  createApiDtoLinkSchema,
  batchCreateApiDtoLinksSchema,
  updateApiDtoLinkSchema,
  listApiDtoLinksSchema,
  idParamSchema,
  apiIdParamSchema,
  dtoIdParamSchema,
} from '../validations/link.validation';

const router = Router();
const controller = new ApiDtoLinkController();

// 基本 CRUD
router.post(
  '/',
  validate(createApiDtoLinkSchema),
  controller.create
);

router.post(
  '/batch',
  validate(batchCreateApiDtoLinksSchema),
  controller.batchCreate
);

router.get(
  '/',
  validate(listApiDtoLinksSchema),
  controller.findMany
);

router.get(
  '/stats',
  controller.getStatistics
);

router.get(
  '/:id',
  validate(idParamSchema),
  controller.findById
);

router.put(
  '/:id',
  validate(updateApiDtoLinkSchema),
  controller.update
);

router.delete(
  '/:id',
  validate(idParamSchema),
  controller.delete
);

// 特殊查詢
router.get(
  '/api/:apiId/dtos',
  validate(apiIdParamSchema),
  controller.findDtosByApi
);

router.get(
  '/dto/:dtoId/apis',
  validate(dtoIdParamSchema),
  controller.findApisByDto
);

// 自動產生
router.post(
  '/api/:apiId/auto-generate',
  validate(apiIdParamSchema),
  controller.autoGenerateDtos
);

export default router;